#!/bin/sh

if [ -f /mnt/hdd0/program/.swap ]; then
	echo "swap file exist!!"
else
	echo "create new swap file. 1G"
	dd if=/dev/zero of=/mnt/hdd0/program/.swap bs=1024 count=1048576
	/sbin/mkswap /mnt/hdd0/program/.swap
fi
